name: Create and upload Conan JDK 11 package

on:
  workflow_dispatch

jobs:
  create-conan-package:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: ['3.9', '3.12.0-alpha.6']

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      
      - name: Install Python Requirements
        run: pip3 install -r requirements.txt

      - name: Check Conan version
        run: conan --version

      - name: Create Conan package
        run: |
          conan create . openjdk/11.0.18@java/stable
          conan install openjdk/11.0.18@java/stable -g=virtualenv
      
      - name: Activate Virtualenv and check JDK version
        if: matrix.os == 'windows-latest'
        run: |
          ./activate.ps1
          java --version
        shell: powershell

      - name: Activate Virtualenv and check JDK version
        if: matrix.os == 'ubuntu-latest'
        run: |
          source activate.sh
          java --version
        shell: bash

      - name: Activate Virtualenv and check JDK version
        if: matrix.os == 'macos-latest'
        run: |
          source activate.sh
          java --version
        shell: bash
